# Generated by Django 3.1.7 on 2021-10-01 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0010_contact_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='totalPrice',
            field=models.IntegerField(default=0),
        ),
    ]
