# Generated by Django 3.1.7 on 2021-10-01 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0012_auto_20211001_1247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='paid',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_id',
        ),
    ]
